name: Install Hadoop
description: Install Hadoop with cloud connectors
branding:
  icon: layers
  color: yellow

inputs:
  version:
    description: The version to install
    required: true
  gcs-connector-version:
    description: The Hadoop Google Cloud Storage connector version to install
    required: false
  aws-module-version:
    description: The Hadoop AWS module version to install
    required: false
  aws-java-sdk-version:
    description: The AWS Java SDK bundle version that was used to compile the Hadoop AWS module
    required: false

runs:
  using: composite
  steps:
    - name: Install Hadoop
      shell: bash
      env:
        ENDPOINT: https://downloads.apache.org/hadoop/common/hadoop
        VERSION: ${{ inputs.version }}
      run: |-
        echo "Installing Hadoop ${VERSION}"
        wget "${ENDPOINT}-${VERSION}/hadoop-${VERSION}.tar.gz" --progress=dot:giga \
          -O /tmp/hadoop.tar.gz
        sudo tar -xzf /tmp/hadoop.tar.gz --directory /opt/
        sudo mv "/opt/hadoop-${VERSION}" /opt/hadoop
        rm /tmp/hadoop.tar.gz

        export HADOOP_HOME="/opt/hadoop"
        echo "HADOOP_HOME=${HADOOP_HOME}" >> $GITHUB_ENV
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}${HADOOP_HOME}/lib/native"
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        export HADOOP_COMMON_LIBS_JAR_DIR="${HADOOP_HOME}/share/hadoop/common/lib"
        echo "HADOOP_COMMON_LIBS_JAR_DIR=${HADOOP_COMMON_LIBS_JAR_DIR}" >> $GITHUB_ENV

    - name: Install Google Cloud Storage connector
      if: inputs.gcs-connector-version != ''
      shell: bash
      env:
        ENDPOINT: https://storage.googleapis.com/hadoop-lib/gcs
        VERSION: ${{ inputs.gcs-connector-version }}
      run: |-
        echo "Installing Google Cloud Storage connector ${VERSION}"
        sudo wget "${ENDPOINT}/gcs-connector-hadoop3-${VERSION}.jar" --progress=dot:giga \
          -O "/opt/hadoop/share/hadoop/common/lib/gcs-connector-hadoop3-${VERSION}.jar"

    - name: Install AWS module
      if: inputs.aws-module-version != ''
      shell: bash
      env:
        MODULE_ENDPOINT: https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws
        MODULE_VERSION: ${{ inputs.aws-module-version }}
        SDK_ENDPOINT: https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle
        SDK_VERSION: ${{ inputs.aws-java-sdk-version }}
      run: |-
        echo "Installing Hadoop AWS module ${MODULE_VERSION}"
        sudo wget "${MODULE_ENDPOINT}/${MODULE_VERSION}/hadoop-aws-${MODULE_VERSION}.jar" \
          --progress=dot:giga \
          -O "/opt/hadoop/share/hadoop/common/lib/hadoop-aws-${AWS_MODULE_VERSION}.jar"

        echo "Installing AWS Java SDK ${SDK_VERSION}"
        sudo wget "${SDK_ENDPOINT}/${SDK_VERSION}/aws-java-sdk-bundle-${SDK_VERSION}.jar" \
          --progress=dot:giga \
          -O "/opt/hadoop/share/hadoop/common/lib/aws-java-sdk-bundle-${SDK_VERSION}.jar"
